# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
# created-by: conda 24.11.3
brotli-python=1.0.9=py313h5da7b33_9
bzip2=1.0.8=h2bbff1b_6
ca-certificates=2025.4.26=h4c7d964_0
certifi=2025.4.26=py313haa95532_0
charset-normalizer=3.3.2=pyhd3eb1b0_0
cuda-cccl=12.8.90=0
cuda-cccl_win-64=12.8.90=0
cuda-cudart=11.8.89=0
cuda-cudart-dev=11.8.89=0
cuda-cupti=11.8.87=0
cuda-libraries=11.8.0=0
cuda-libraries-dev=11.8.0=0
cuda-nvrtc=11.8.89=0
cuda-nvrtc-dev=11.8.89=0
cuda-nvtx=11.8.86=0
cuda-profiler-api=12.8.90=0
cuda-runtime=11.8.0=0
cuda-version=12.8=3
expat=2.7.1=h8ddb27b_0
idna=3.7=py313haa95532_0
libcublas=11.11.3.6=0
libcublas-dev=11.11.3.6=0
libcufft=10.9.0.58=0
libcufft-dev=10.9.0.58=0
libcurand=10.3.9.90=0
libcurand-dev=10.3.9.90=0
libcusolver=11.4.1.48=0
libcusolver-dev=11.4.1.48=0
libcusparse=11.7.5.86=0
libcusparse-dev=11.7.5.86=0
libffi=3.4.4=hd77b12b_1
libmpdec=4.0.0=h827c3e9_0
libnpp=11.8.0.86=0
libnpp-dev=11.8.0.86=0
libnvjpeg=11.9.0.86=0
libnvjpeg-dev=11.9.0.86=0
linkify-it-py=2.0.3=pyhd8ed1ab_1
markdown-it-py=3.0.0=pyhd8ed1ab_1
mdit-py-plugins=0.4.2=pyhd8ed1ab_1
mdurl=0.1.2=pyhd8ed1ab_1
openssl=3.5.0=ha4e3fda_0
pip=25.1=pyh0d26453_0
platformdirs=4.3.7=pyh29332c3_0
psutil=7.0.0=pypi_0
pygments=2.19.1=pyhd8ed1ab_0
pysocks=1.7.1=py313haa95532_0
python=3.13.2=hadb2040_100_cp313
python-dotenv=1.1.0=pyh29332c3_1
python_abi=3.13=0_cp313
pytorch-cuda=11.8=h24eeafa_6
requests=2.32.3=py313haa95532_1
rich=14.0.0=pyh29332c3_0
sqlite=3.45.3=h2bbff1b_0
textual=3.1.1=pyhd8ed1ab_0
tk=8.6.14=h0416ee5_0
torch=2.7.0=pypi_0
typing-extensions=4.13.2=h0e9735f_0
typing_extensions=4.13.2=pyh29332c3_0
tzdata=2025a=h04d1e81_0
uc-micro-py=1.0.3=pyhd8ed1ab_1
ucrt=10.0.22621.0=h57928b3_1
urllib3=2.3.0=py313haa95532_0
vc=14.42=haa95532_5
vc14_runtime=14.42.34438=hfd919c2_26
vs2015_runtime=14.42.34438=h7142326_26
wheel=0.45.1=pypi_0
win_inet_pton=1.1.0=py313haa95532_0
xz=5.6.4=h4754444_1
zlib=1.2.13=h8cc25b3_1